/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MehfilRouteImport } from './routes/mehfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DmRouteImport } from './routes/dm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as MehfilIdRouteImport } from './routes/mehfil.$id'
import { Route as DmUidRouteImport } from './routes/dm.$uid'

const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MehfilRoute = MehfilRouteImport.update({
  id: '/mehfil',
  path: '/mehfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DmRoute = DmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MehfilIdRoute = MehfilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MehfilRoute,
} as any)
const DmUidRoute = DmUidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => DmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dm': typeof DmRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mehfil': typeof MehfilRouteWithChildren
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/dm/$uid': typeof DmUidRoute
  '/mehfil/$id': typeof MehfilIdRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dm': typeof DmRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mehfil': typeof MehfilRouteWithChildren
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/dm/$uid': typeof DmUidRoute
  '/mehfil/$id': typeof MehfilIdRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dm': typeof DmRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mehfil': typeof MehfilRouteWithChildren
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/dm/$uid': typeof DmUidRoute
  '/mehfil/$id': typeof MehfilIdRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dm'
    | '/home'
    | '/login'
    | '/mehfil'
    | '/profile'
    | '/record'
    | '/dm/$uid'
    | '/mehfil/$id'
    | '/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dm'
    | '/home'
    | '/login'
    | '/mehfil'
    | '/profile'
    | '/record'
    | '/dm/$uid'
    | '/mehfil/$id'
    | '/story/$id'
  id:
    | '__root__'
    | '/'
    | '/dm'
    | '/home'
    | '/login'
    | '/mehfil'
    | '/profile'
    | '/record'
    | '/dm/$uid'
    | '/mehfil/$id'
    | '/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DmRoute: typeof DmRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MehfilRoute: typeof MehfilRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRoute
  StoryIdRoute: typeof StoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehfil': {
      id: '/mehfil'
      path: '/mehfil'
      fullPath: '/mehfil'
      preLoaderRoute: typeof MehfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm': {
      id: '/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof DmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehfil/$id': {
      id: '/mehfil/$id'
      path: '/$id'
      fullPath: '/mehfil/$id'
      preLoaderRoute: typeof MehfilIdRouteImport
      parentRoute: typeof MehfilRoute
    }
    '/dm/$uid': {
      id: '/dm/$uid'
      path: '/$uid'
      fullPath: '/dm/$uid'
      preLoaderRoute: typeof DmUidRouteImport
      parentRoute: typeof DmRoute
    }
  }
}

interface DmRouteChildren {
  DmUidRoute: typeof DmUidRoute
}

const DmRouteChildren: DmRouteChildren = {
  DmUidRoute: DmUidRoute,
}

const DmRouteWithChildren = DmRoute._addFileChildren(DmRouteChildren)

interface MehfilRouteChildren {
  MehfilIdRoute: typeof MehfilIdRoute
}

const MehfilRouteChildren: MehfilRouteChildren = {
  MehfilIdRoute: MehfilIdRoute,
}

const MehfilRouteWithChildren =
  MehfilRoute._addFileChildren(MehfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DmRoute: DmRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MehfilRoute: MehfilRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRoute,
  StoryIdRoute: StoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
